name: CoQuest
version: 1.0
author: Cotax
main: fr.cotax.coquest.main
api-version: 1.15
commands:
  test:
    description: Basicaly, a test command
  alert:
    description: Un broadcast custom
  quest:
    description: Command to see quest